//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *RealmKeysParameters) DeepCopyInto(out *RealmKeysParameters) {
	*out = *in
}

func (in *RealmKeysSpec) DeepCopyInto(out *RealmKeysSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *RealmKeysStatus) DeepCopyInto(out *RealmKeysStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]KeyInfo, len(*in))
		copy(*out, *in)
	}
}

func (in *RealmKeys) DeepCopyInto(out *RealmKeys) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RealmKeys) DeepCopy() *RealmKeys {
	if in == nil {
		return nil
	}
	out := new(RealmKeys)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmKeys) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RealmKeysList) DeepCopyInto(out *RealmKeysList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealmKeys, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RealmKeysList) DeepCopy() *RealmKeysList {
	if in == nil {
		return nil
	}
	out := new(RealmKeysList)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmKeysList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
