//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitialAccess) DeepCopyInto(out *ClientInitialAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitialAccess.
func (in *ClientInitialAccess) DeepCopy() *ClientInitialAccess {
	if in == nil {
		return nil
	}
	out := new(ClientInitialAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientInitialAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitialAccessList) DeepCopyInto(out *ClientInitialAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientInitialAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitialAccessList.
func (in *ClientInitialAccessList) DeepCopy() *ClientInitialAccessList {
	if in == nil {
		return nil
	}
	out := new(ClientInitialAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientInitialAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitialAccessParameters) DeepCopyInto(out *ClientInitialAccessParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitialAccessParameters.
func (in *ClientInitialAccessParameters) DeepCopy() *ClientInitialAccessParameters {
	if in == nil {
		return nil
	}
	out := new(ClientInitialAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitialAccessSpec) DeepCopyInto(out *ClientInitialAccessSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitialAccessSpec.
func (in *ClientInitialAccessSpec) DeepCopy() *ClientInitialAccessSpec {
	if in == nil {
		return nil
	}
	out := new(ClientInitialAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitialAccessStatus) DeepCopyInto(out *ClientInitialAccessStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitialAccessStatus.
func (in *ClientInitialAccessStatus) DeepCopy() *ClientInitialAccessStatus {
	if in == nil {
		return nil
	}
	out := new(ClientInitialAccessStatus)
	in.DeepCopyInto(out)
	return out
}
