//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *RealmEventsConfigParameters) DeepCopyInto(out *RealmEventsConfigParameters) {
	*out = *in
	if in.EventsEnabled != nil {
		in, out := &in.EventsEnabled, &out.EventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EventsExpiration != nil {
		in, out := &in.EventsExpiration, &out.EventsExpiration
		*out = new(int64)
		**out = **in
	}
	if in.EventsListeners != nil {
		in, out := &in.EventsListeners, &out.EventsListeners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnabledEvents != nil {
		in, out := &in.EnabledEvents, &out.EnabledEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminEventsEnabled != nil {
		in, out := &in.AdminEventsEnabled, &out.AdminEventsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AdminEventsDetailsEnabled != nil {
		in, out := &in.AdminEventsDetailsEnabled, &out.AdminEventsDetailsEnabled
		*out = new(bool)
		**out = **in
	}
}

func (in *RealmEventsConfigSpec) DeepCopyInto(out *RealmEventsConfigSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *RealmEventsConfigStatus) DeepCopyInto(out *RealmEventsConfigStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

func (in *RealmEventsConfig) DeepCopyInto(out *RealmEventsConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RealmEventsConfig) DeepCopy() *RealmEventsConfig {
	if in == nil { return nil }
	out := new(RealmEventsConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmEventsConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RealmEventsConfigList) DeepCopyInto(out *RealmEventsConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealmEventsConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RealmEventsConfigList) DeepCopy() *RealmEventsConfigList {
	if in == nil { return nil }
	out := new(RealmEventsConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmEventsConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}