//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	xpv1 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *FederatedIdentity) DeepCopyInto(out *FederatedIdentity) {
	*out = *in
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UserParameters) DeepCopyInto(out *UserParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.EmailVerified != nil {
		in, out := &in.EmailVerified, &out.EmailVerified
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FirstName != nil {
		in, out := &in.FirstName, &out.FirstName
		*out = new(string)
		**out = **in
	}
	if in.LastName != nil {
		in, out := &in.LastName, &out.LastName
		*out = new(string)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.RequiredActions != nil {
		in, out := &in.RequiredActions, &out.RequiredActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FederatedIdentity != nil {
		in, out := &in.FederatedIdentity, &out.FederatedIdentity
		*out = make([]FederatedIdentity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GroupsParameters) DeepCopyInto(out *GroupsParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserId != nil {
		in, out := &in.UserId, &out.UserId
		*out = new(string)
		**out = **in
	}
	if in.UserIdRef != nil {
		in, out := &in.UserIdRef, &out.UserIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserIdSelector != nil {
		in, out := &in.UserIdSelector, &out.UserIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupIds != nil {
		in, out := &in.GroupIds, &out.GroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GroupIdsRefs != nil {
		in, out := &in.GroupIdsRefs, &out.GroupIdsRefs
		*out = make([]xpv1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupIdsSelector != nil {
		in, out := &in.GroupIdsSelector, &out.GroupIdsSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Exhaustive != nil {
		in, out := &in.Exhaustive, &out.Exhaustive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GroupsSpec) DeepCopyInto(out *GroupsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GroupsStatus) DeepCopyInto(out *GroupsStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Groups) DeepCopyInto(out *Groups) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this Groups.
func (in *Groups) DeepCopy() *Groups {
	if in == nil {
		return nil
	}
	out := new(Groups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Groups) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *GroupsList) DeepCopyInto(out *GroupsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Groups, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this GroupsList.
func (in *GroupsList) DeepCopy() *GroupsList {
	if in == nil {
		return nil
	}
	out := new(GroupsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GroupsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
