//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyInfo) DeepCopyInto(out *KeyInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyInfo.
func (in *KeyInfo) DeepCopy() *KeyInfo {
	if in == nil {
		return nil
	}
	out := new(KeyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmKeys) DeepCopyInto(out *RealmKeys) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmKeys.
func (in *RealmKeys) DeepCopy() *RealmKeys {
	if in == nil {
		return nil
	}
	out := new(RealmKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmKeys) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmKeysList) DeepCopyInto(out *RealmKeysList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealmKeys, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmKeysList.
func (in *RealmKeysList) DeepCopy() *RealmKeysList {
	if in == nil {
		return nil
	}
	out := new(RealmKeysList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmKeysList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmKeysParameters) DeepCopyInto(out *RealmKeysParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmKeysParameters.
func (in *RealmKeysParameters) DeepCopy() *RealmKeysParameters {
	if in == nil {
		return nil
	}
	out := new(RealmKeysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmKeysSpec) DeepCopyInto(out *RealmKeysSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmKeysSpec.
func (in *RealmKeysSpec) DeepCopy() *RealmKeysSpec {
	if in == nil {
		return nil
	}
	out := new(RealmKeysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmKeysStatus) DeepCopyInto(out *RealmKeysStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]KeyInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmKeysStatus.
func (in *RealmKeysStatus) DeepCopy() *RealmKeysStatus {
	if in == nil {
		return nil
	}
	out := new(RealmKeysStatus)
	in.DeepCopyInto(out)
	return out
}
