// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this RealmImport.
func (mg *RealmImport) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetManagementPolicies of this RealmImport.
func (mg *RealmImport) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this RealmImport.
func (mg *RealmImport) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this RealmImport.
func (mg *RealmImport) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this RealmImport.
func (mg *RealmImport) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetManagementPolicies of this RealmImport.
func (mg *RealmImport) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this RealmImport.
func (mg *RealmImport) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this RealmImport.
func (mg *RealmImport) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
