//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClientInitialAccessParameters) DeepCopyInto(out *ClientInitialAccessParameters) {
	*out = *in
}

func (in *ClientInitialAccessSpec) DeepCopyInto(out *ClientInitialAccessSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *ClientInitialAccessStatus) DeepCopyInto(out *ClientInitialAccessStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

func (in *ClientInitialAccess) DeepCopyInto(out *ClientInitialAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClientInitialAccess) DeepCopy() *ClientInitialAccess {
	if in == nil { return nil }
	out := new(ClientInitialAccess)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientInitialAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ClientInitialAccessList) DeepCopyInto(out *ClientInitialAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientInitialAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClientInitialAccessList) DeepCopy() *ClientInitialAccessList {
	if in == nil { return nil }
	out := new(ClientInitialAccessList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientInitialAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}