//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Realm) DeepCopyInto(out *Realm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Realm.
func (in *Realm) DeepCopy() *Realm {
	if in == nil {
		return nil
	}
	out := new(Realm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Realm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmList) DeepCopyInto(out *RealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Realm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmList.
func (in *RealmList) DeepCopy() *RealmList {
	if in == nil {
		return nil
	}
	out := new(RealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmParameters) DeepCopyInto(out *RealmParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DisplayNameHtml != nil {
		in, out := &in.DisplayNameHtml, &out.DisplayNameHtml
		*out = new(string)
		**out = **in
	}
	if in.SslRequired != nil {
		in, out := &in.SslRequired, &out.SslRequired
		*out = new(string)
		**out = **in
	}
	if in.RegistrationAllowed != nil {
		in, out := &in.RegistrationAllowed, &out.RegistrationAllowed
		*out = new(bool)
		**out = **in
	}
	if in.RegistrationEmailAsUsername != nil {
		in, out := &in.RegistrationEmailAsUsername, &out.RegistrationEmailAsUsername
		*out = new(bool)
		**out = **in
	}
	if in.EditUsernameAllowed != nil {
		in, out := &in.EditUsernameAllowed, &out.EditUsernameAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordAllowed != nil {
		in, out := &in.ResetPasswordAllowed, &out.ResetPasswordAllowed
		*out = new(bool)
		**out = **in
	}
	if in.RememberMe != nil {
		in, out := &in.RememberMe, &out.RememberMe
		*out = new(bool)
		**out = **in
	}
	if in.VerifyEmail != nil {
		in, out := &in.VerifyEmail, &out.VerifyEmail
		*out = new(bool)
		**out = **in
	}
	if in.LoginWithEmailAllowed != nil {
		in, out := &in.LoginWithEmailAllowed, &out.LoginWithEmailAllowed
		*out = new(bool)
		**out = **in
	}
	if in.DuplicateEmailsAllowed != nil {
		in, out := &in.DuplicateEmailsAllowed, &out.DuplicateEmailsAllowed
		*out = new(bool)
		**out = **in
	}
	if in.DefaultSignatureAlgorithm != nil {
		in, out := &in.DefaultSignatureAlgorithm, &out.DefaultSignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.RevokeRefreshToken != nil {
		in, out := &in.RevokeRefreshToken, &out.RevokeRefreshToken
		*out = new(bool)
		**out = **in
	}
	if in.RefreshTokenMaxReuse != nil {
		in, out := &in.RefreshTokenMaxReuse, &out.RefreshTokenMaxReuse
		*out = new(int64)
		**out = **in
	}
	if in.AccessTokenLifespan != nil {
		in, out := &in.AccessTokenLifespan, &out.AccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenLifespanForImplicitFlow != nil {
		in, out := &in.AccessTokenLifespanForImplicitFlow, &out.AccessTokenLifespanForImplicitFlow
		*out = new(string)
		**out = **in
	}
	if in.SsoSessionIdleTimeout != nil {
		in, out := &in.SsoSessionIdleTimeout, &out.SsoSessionIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.SsoSessionMaxLifespan != nil {
		in, out := &in.SsoSessionMaxLifespan, &out.SsoSessionMaxLifespan
		*out = new(string)
		**out = **in
	}
	if in.SsoSessionIdleTimeoutRememberMe != nil {
		in, out := &in.SsoSessionIdleTimeoutRememberMe, &out.SsoSessionIdleTimeoutRememberMe
		*out = new(string)
		**out = **in
	}
	if in.SsoSessionMaxLifespanRememberMe != nil {
		in, out := &in.SsoSessionMaxLifespanRememberMe, &out.SsoSessionMaxLifespanRememberMe
		*out = new(string)
		**out = **in
	}
	if in.OfflineSessionIdleTimeout != nil {
		in, out := &in.OfflineSessionIdleTimeout, &out.OfflineSessionIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.OfflineSessionMaxLifespanEnabled != nil {
		in, out := &in.OfflineSessionMaxLifespanEnabled, &out.OfflineSessionMaxLifespanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OfflineSessionMaxLifespan != nil {
		in, out := &in.OfflineSessionMaxLifespan, &out.OfflineSessionMaxLifespan
		*out = new(string)
		**out = **in
	}
	if in.ClientSessionIdleTimeout != nil {
		in, out := &in.ClientSessionIdleTimeout, &out.ClientSessionIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.ClientSessionMaxLifespan != nil {
		in, out := &in.ClientSessionMaxLifespan, &out.ClientSessionMaxLifespan
		*out = new(string)
		**out = **in
	}
	if in.AccessCodeLifespan != nil {
		in, out := &in.AccessCodeLifespan, &out.AccessCodeLifespan
		*out = new(string)
		**out = **in
	}
	if in.AccessCodeLifespanUserAction != nil {
		in, out := &in.AccessCodeLifespanUserAction, &out.AccessCodeLifespanUserAction
		*out = new(string)
		**out = **in
	}
	if in.AccessCodeLifespanLogin != nil {
		in, out := &in.AccessCodeLifespanLogin, &out.AccessCodeLifespanLogin
		*out = new(string)
		**out = **in
	}
	if in.ActionTokenGeneratedByAdminLifespan != nil {
		in, out := &in.ActionTokenGeneratedByAdminLifespan, &out.ActionTokenGeneratedByAdminLifespan
		*out = new(string)
		**out = **in
	}
	if in.ActionTokenGeneratedByUserLifespan != nil {
		in, out := &in.ActionTokenGeneratedByUserLifespan, &out.ActionTokenGeneratedByUserLifespan
		*out = new(string)
		**out = **in
	}
	if in.LoginTheme != nil {
		in, out := &in.LoginTheme, &out.LoginTheme
		*out = new(string)
		**out = **in
	}
	if in.AccountTheme != nil {
		in, out := &in.AccountTheme, &out.AccountTheme
		*out = new(string)
		**out = **in
	}
	if in.AdminTheme != nil {
		in, out := &in.AdminTheme, &out.AdminTheme
		*out = new(string)
		**out = **in
	}
	if in.EmailTheme != nil {
		in, out := &in.EmailTheme, &out.EmailTheme
		*out = new(string)
		**out = **in
	}
	if in.FrontendURL != nil {
		in, out := &in.FrontendURL, &out.FrontendURL
		*out = new(string)
		**out = **in
	}
	if in.SmtpServer != nil {
		in, out := &in.SmtpServer, &out.SmtpServer
		*out = make([]SmtpServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PasswordPolicy != nil {
		in, out := &in.PasswordPolicy, &out.PasswordPolicy
		*out = new(string)
		**out = **in
	}
	if in.DefaultDefaultClientScopes != nil {
		in, out := &in.DefaultDefaultClientScopes, &out.DefaultDefaultClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultOptionalClientScopes != nil {
		in, out := &in.DefaultOptionalClientScopes, &out.DefaultOptionalClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BrowserFlow != nil {
		in, out := &in.BrowserFlow, &out.BrowserFlow
		*out = new(string)
		**out = **in
	}
	if in.RegistrationFlow != nil {
		in, out := &in.RegistrationFlow, &out.RegistrationFlow
		*out = new(string)
		**out = **in
	}
	if in.DirectGrantFlow != nil {
		in, out := &in.DirectGrantFlow, &out.DirectGrantFlow
		*out = new(string)
		**out = **in
	}
	if in.ResetCredentialsFlow != nil {
		in, out := &in.ResetCredentialsFlow, &out.ResetCredentialsFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientAuthenticationFlow != nil {
		in, out := &in.ClientAuthenticationFlow, &out.ClientAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.UserManagedAccess != nil {
		in, out := &in.UserManagedAccess, &out.UserManagedAccess
		*out = new(bool)
		**out = **in
	}
	if in.AdminPermissionsEnabled != nil {
		in, out := &in.AdminPermissionsEnabled, &out.AdminPermissionsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmParameters.
func (in *RealmParameters) DeepCopy() *RealmParameters {
	if in == nil {
		return nil
	}
	out := new(RealmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmSpec) DeepCopyInto(out *RealmSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmSpec.
func (in *RealmSpec) DeepCopy() *RealmSpec {
	if in == nil {
		return nil
	}
	out := new(RealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealmStatus) DeepCopyInto(out *RealmStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealmStatus.
func (in *RealmStatus) DeepCopy() *RealmStatus {
	if in == nil {
		return nil
	}
	out := new(RealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmtpPasswordSecretRef) DeepCopyInto(out *SmtpPasswordSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmtpPasswordSecretRef.
func (in *SmtpPasswordSecretRef) DeepCopy() *SmtpPasswordSecretRef {
	if in == nil {
		return nil
	}
	out := new(SmtpPasswordSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmtpServer) DeepCopyInto(out *SmtpServer) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(string)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromDisplayName != nil {
		in, out := &in.FromDisplayName, &out.FromDisplayName
		*out = new(string)
		**out = **in
	}
	if in.ReplyTo != nil {
		in, out := &in.ReplyTo, &out.ReplyTo
		*out = new(string)
		**out = **in
	}
	if in.ReplyToDisplayName != nil {
		in, out := &in.ReplyToDisplayName, &out.ReplyToDisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnvelopeFrom != nil {
		in, out := &in.EnvelopeFrom, &out.EnvelopeFrom
		*out = new(string)
		**out = **in
	}
	if in.Ssl != nil {
		in, out := &in.Ssl, &out.Ssl
		*out = new(bool)
		**out = **in
	}
	if in.Starttls != nil {
		in, out := &in.Starttls, &out.Starttls
		*out = new(bool)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = make([]SmtpServerAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmtpServer.
func (in *SmtpServer) DeepCopy() *SmtpServer {
	if in == nil {
		return nil
	}
	out := new(SmtpServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmtpServerAuth) DeepCopyInto(out *SmtpServerAuth) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SmtpPasswordSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmtpServerAuth.
func (in *SmtpServerAuth) DeepCopy() *SmtpServerAuth {
	if in == nil {
		return nil
	}
	out := new(SmtpServerAuth)
	in.DeepCopyInto(out)
	return out
}
