//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane/apis/v2/core/v2"

	"k8s.io/apimachinery/pkg/runtime"
)

// deepcopyRef is a helper to avoid the unused import warning.
var _ = xpv1.Reference{}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SmtpPasswordSecretRef) DeepCopyInto(out *SmtpPasswordSecretRef) {
	*out = *in
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SmtpServerAuth) DeepCopyInto(out *SmtpServerAuth) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SmtpPasswordSecretRef)
		**out = **in
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SmtpServer) DeepCopyInto(out *SmtpServer) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(string)
		**out = **in
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromDisplayName != nil {
		in, out := &in.FromDisplayName, &out.FromDisplayName
		*out = new(string)
		**out = **in
	}
	if in.ReplyTo != nil {
		in, out := &in.ReplyTo, &out.ReplyTo
		*out = new(string)
		**out = **in
	}
	if in.ReplyToDisplayName != nil {
		in, out := &in.ReplyToDisplayName, &out.ReplyToDisplayName
		*out = new(string)
		**out = **in
	}
	if in.EnvelopeFrom != nil {
		in, out := &in.EnvelopeFrom, &out.EnvelopeFrom
		*out = new(string)
		**out = **in
	}
	if in.Ssl != nil {
		in, out := &in.Ssl, &out.Ssl
		*out = new(bool)
		**out = **in
	}
	if in.Starttls != nil {
		in, out := &in.Starttls, &out.Starttls
		*out = new(bool)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = make([]SmtpServerAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func deepCopyStringPtr(in *string) *string {
	if in == nil {
		return nil
	}
	out := new(string)
	*out = *in
	return out
}

func deepCopyBoolPtr(in *bool) *bool {
	if in == nil {
		return nil
	}
	out := new(bool)
	*out = *in
	return out
}

func deepCopyInt64Ptr(in *int64) *int64 {
	if in == nil {
		return nil
	}
	out := new(int64)
	*out = *in
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RealmParameters) DeepCopyInto(out *RealmParameters) {
	*out = *in
	out.Realm = in.Realm
	out.Enabled = deepCopyBoolPtr(in.Enabled)
	out.DisplayName = deepCopyStringPtr(in.DisplayName)
	out.DisplayNameHtml = deepCopyStringPtr(in.DisplayNameHtml)
	out.SslRequired = deepCopyStringPtr(in.SslRequired)
	out.RegistrationAllowed = deepCopyBoolPtr(in.RegistrationAllowed)
	out.RegistrationEmailAsUsername = deepCopyBoolPtr(in.RegistrationEmailAsUsername)
	out.EditUsernameAllowed = deepCopyBoolPtr(in.EditUsernameAllowed)
	out.ResetPasswordAllowed = deepCopyBoolPtr(in.ResetPasswordAllowed)
	out.RememberMe = deepCopyBoolPtr(in.RememberMe)
	out.VerifyEmail = deepCopyBoolPtr(in.VerifyEmail)
	out.LoginWithEmailAllowed = deepCopyBoolPtr(in.LoginWithEmailAllowed)
	out.DuplicateEmailsAllowed = deepCopyBoolPtr(in.DuplicateEmailsAllowed)
	out.DefaultSignatureAlgorithm = deepCopyStringPtr(in.DefaultSignatureAlgorithm)
	out.RevokeRefreshToken = deepCopyBoolPtr(in.RevokeRefreshToken)
	out.RefreshTokenMaxReuse = deepCopyInt64Ptr(in.RefreshTokenMaxReuse)
	out.AccessTokenLifespan = deepCopyStringPtr(in.AccessTokenLifespan)
	out.AccessTokenLifespanForImplicitFlow = deepCopyStringPtr(in.AccessTokenLifespanForImplicitFlow)
	out.SsoSessionIdleTimeout = deepCopyStringPtr(in.SsoSessionIdleTimeout)
	out.SsoSessionMaxLifespan = deepCopyStringPtr(in.SsoSessionMaxLifespan)
	out.SsoSessionIdleTimeoutRememberMe = deepCopyStringPtr(in.SsoSessionIdleTimeoutRememberMe)
	out.SsoSessionMaxLifespanRememberMe = deepCopyStringPtr(in.SsoSessionMaxLifespanRememberMe)
	out.OfflineSessionIdleTimeout = deepCopyStringPtr(in.OfflineSessionIdleTimeout)
	out.OfflineSessionMaxLifespanEnabled = deepCopyBoolPtr(in.OfflineSessionMaxLifespanEnabled)
	out.OfflineSessionMaxLifespan = deepCopyStringPtr(in.OfflineSessionMaxLifespan)
	out.ClientSessionIdleTimeout = deepCopyStringPtr(in.ClientSessionIdleTimeout)
	out.ClientSessionMaxLifespan = deepCopyStringPtr(in.ClientSessionMaxLifespan)
	out.AccessCodeLifespan = deepCopyStringPtr(in.AccessCodeLifespan)
	out.AccessCodeLifespanUserAction = deepCopyStringPtr(in.AccessCodeLifespanUserAction)
	out.AccessCodeLifespanLogin = deepCopyStringPtr(in.AccessCodeLifespanLogin)
	out.ActionTokenGeneratedByAdminLifespan = deepCopyStringPtr(in.ActionTokenGeneratedByAdminLifespan)
	out.ActionTokenGeneratedByUserLifespan = deepCopyStringPtr(in.ActionTokenGeneratedByUserLifespan)
	out.LoginTheme = deepCopyStringPtr(in.LoginTheme)
	out.AccountTheme = deepCopyStringPtr(in.AccountTheme)
	out.AdminTheme = deepCopyStringPtr(in.AdminTheme)
	out.EmailTheme = deepCopyStringPtr(in.EmailTheme)
	out.PasswordPolicy = deepCopyStringPtr(in.PasswordPolicy)
	out.BrowserFlow = deepCopyStringPtr(in.BrowserFlow)
	out.RegistrationFlow = deepCopyStringPtr(in.RegistrationFlow)
	out.DirectGrantFlow = deepCopyStringPtr(in.DirectGrantFlow)
	out.ResetCredentialsFlow = deepCopyStringPtr(in.ResetCredentialsFlow)
	out.ClientAuthenticationFlow = deepCopyStringPtr(in.ClientAuthenticationFlow)
	out.UserManagedAccess = deepCopyBoolPtr(in.UserManagedAccess)
	out.AdminPermissionsEnabled = deepCopyBoolPtr(in.AdminPermissionsEnabled)
	if in.SmtpServer != nil {
		in, out := &in.SmtpServer, &out.SmtpServer
		*out = make([]SmtpServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DefaultDefaultClientScopes != nil {
		in, out := &in.DefaultDefaultClientScopes, &out.DefaultDefaultClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultOptionalClientScopes != nil {
		in, out := &in.DefaultOptionalClientScopes, &out.DefaultOptionalClientScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RealmSpec) DeepCopyInto(out *RealmSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RealmStatus) DeepCopyInto(out *RealmStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Realm) DeepCopyInto(out *Realm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this Realm.
func (in *Realm) DeepCopy() *Realm {
	if in == nil {
		return nil
	}
	out := new(Realm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Realm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *RealmList) DeepCopyInto(out *RealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Realm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this RealmList.
func (in *RealmList) DeepCopy() *RealmList {
	if in == nil {
		return nil
	}
	out := new(RealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *RealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
