//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapper) DeepCopyInto(out *ProtocolMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapper.
func (in *ProtocolMapper) DeepCopy() *ProtocolMapper {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtocolMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapperList) DeepCopyInto(out *ProtocolMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapperList.
func (in *ProtocolMapperList) DeepCopy() *ProtocolMapperList {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtocolMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapperParameters) DeepCopyInto(out *ProtocolMapperParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.ClientIdRef != nil {
		in, out := &in.ClientIdRef, &out.ClientIdRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientIdSelector != nil {
		in, out := &in.ClientIdSelector, &out.ClientIdSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientScopeId != nil {
		in, out := &in.ClientScopeId, &out.ClientScopeId
		*out = new(string)
		**out = **in
	}
	if in.ClientScopeIdRef != nil {
		in, out := &in.ClientScopeIdRef, &out.ClientScopeIdRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientScopeIdSelector != nil {
		in, out := &in.ClientScopeIdSelector, &out.ClientScopeIdSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapperParameters.
func (in *ProtocolMapperParameters) DeepCopy() *ProtocolMapperParameters {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapperParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapperSpec) DeepCopyInto(out *ProtocolMapperSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapperSpec.
func (in *ProtocolMapperSpec) DeepCopy() *ProtocolMapperSpec {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolMapperStatus) DeepCopyInto(out *ProtocolMapperStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolMapperStatus.
func (in *ProtocolMapperStatus) DeepCopy() *ProtocolMapperStatus {
	if in == nil {
		return nil
	}
	out := new(ProtocolMapperStatus)
	in.DeepCopyInto(out)
	return out
}
