//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *RealmImportParameters) DeepCopyInto(out *RealmImportParameters) {
	*out = *in
	if in.IfNotExists != nil {
		in, out := &in.IfNotExists, &out.IfNotExists
		*out = new(bool)
		**out = **in
	}
}

func (in *RealmImportSpec) DeepCopyInto(out *RealmImportSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *RealmImportStatus) DeepCopyInto(out *RealmImportStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

func (in *RealmImport) DeepCopyInto(out *RealmImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RealmImport) DeepCopy() *RealmImport {
	if in == nil { return nil }
	out := new(RealmImport)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *RealmImportList) DeepCopyInto(out *RealmImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RealmImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RealmImportList) DeepCopy() *RealmImportList {
	if in == nil { return nil }
	out := new(RealmImportList)
	in.DeepCopyInto(out)
	return out
}

func (in *RealmImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}