//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClientScopeMappingParameters) DeepCopyInto(out *ClientScopeMappingParameters) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]ScopeMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *ClientScopeMappingSpec) DeepCopyInto(out *ClientScopeMappingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *ClientScopeMappingStatus) DeepCopyInto(out *ClientScopeMappingStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.AppliedScopes != nil {
		in, out := &in.AppliedScopes, &out.AppliedScopes
		*out = make([]ScopeMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *ClientScopeMapping) DeepCopyInto(out *ClientScopeMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClientScopeMapping) DeepCopy() *ClientScopeMapping {
	if in == nil { return nil }
	out := new(ClientScopeMapping)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientScopeMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ClientScopeMappingList) DeepCopyInto(out *ClientScopeMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientScopeMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClientScopeMappingList) DeepCopy() *ClientScopeMappingList {
	if in == nil { return nil }
	out := new(ClientScopeMappingList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientScopeMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}