//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClientRoleMappingParameters) DeepCopyInto(out *ClientRoleMappingParameters) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RoleMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *ClientRoleMappingSpec) DeepCopyInto(out *ClientRoleMappingSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *ClientRoleMappingStatus) DeepCopyInto(out *ClientRoleMappingStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	if in.AppliedRoles != nil {
		in, out := &in.AppliedRoles, &out.AppliedRoles
		*out = make([]RoleMapping, len(*in))
		copy(*out, *in)
	}
}

func (in *ClientRoleMapping) DeepCopyInto(out *ClientRoleMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClientRoleMapping) DeepCopy() *ClientRoleMapping {
	if in == nil { return nil }
	out := new(ClientRoleMapping)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientRoleMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}

func (in *ClientRoleMappingList) DeepCopyInto(out *ClientRoleMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientRoleMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClientRoleMappingList) DeepCopy() *ClientRoleMappingList {
	if in == nil { return nil }
	out := new(ClientRoleMappingList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClientRoleMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil { return c }
	return nil
}