//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *AuthzResourceParameters) DeepCopyInto(out *AuthzResourceParameters) {
	*out = *in
	if in.URIs != nil {
		in, out := &in.URIs, &out.URIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.IconURI != nil {
		in, out := &in.IconURI, &out.IconURI
		*out = new(string)
		**out = **in
	}
}

func (in *AuthzResourceSpec) DeepCopyInto(out *AuthzResourceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *AuthzResourceStatus) DeepCopyInto(out *AuthzResourceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

func (in *AuthzResource) DeepCopyInto(out *AuthzResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AuthzResource) DeepCopy() *AuthzResource {
	if in == nil {
		return nil
	}
	out := new(AuthzResource)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthzResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AuthzResourceList) DeepCopyInto(out *AuthzResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthzResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AuthzResourceList) DeepCopy() *AuthzResourceList {
	if in == nil {
		return nil
	}
	out := new(AuthzResourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *AuthzResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
