// Code generated by hand. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	GroupVersion = schema.GroupVersion{Group: "keycloak.crossplane.io", Version: "v1beta1"}

	ClientGroupVersionKind = GroupVersion.WithKind("Client").GroupKind()

	ClientKind = ClientGroupVersionKind.Kind
)

func AddToScheme(s *runtime.Scheme) error {
	return nil
}