//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *UserFederationProviderParameters) DeepCopyInto(out *UserFederationProviderParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

func (in *UserFederationProviderSpec) DeepCopyInto(out *UserFederationProviderSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

func (in *UserFederationProviderStatus) DeepCopyInto(out *UserFederationProviderStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

func (in *UserFederationProvider) DeepCopyInto(out *UserFederationProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *UserFederationProvider) DeepCopy() *UserFederationProvider {
	if in == nil {
		return nil
	}
	out := new(UserFederationProvider)
	in.DeepCopyInto(out)
	return out
}

func (in *UserFederationProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *UserFederationProviderList) DeepCopyInto(out *UserFederationProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserFederationProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *UserFederationProviderList) DeepCopy() *UserFederationProviderList {
	if in == nil {
		return nil
	}
	out := new(UserFederationProviderList)
	in.DeepCopyInto(out)
	return out
}

func (in *UserFederationProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
