//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane/apis/v2/core/v2"

	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientSecretSecretRef) DeepCopyInto(out *ClientSecretSecretRef) {
	*out = *in
}

// DeepCopy returns a deep copy of this ClientSecretSecretRef.
func (in *ClientSecretSecretRef) DeepCopy() *ClientSecretSecretRef {
	if in == nil {
		return nil
	}
	out := new(ClientSecretSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientParameters) DeepCopyInto(out *ClientParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessType != nil {
		in, out := &in.AccessType, &out.AccessType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RootUrl != nil {
		in, out := &in.RootUrl, &out.RootUrl
		*out = new(string)
		**out = **in
	}
	if in.BaseUrl != nil {
		in, out := &in.BaseUrl, &out.BaseUrl
		*out = new(string)
		**out = **in
	}
	if in.AdminUrl != nil {
		in, out := &in.AdminUrl, &out.AdminUrl
		*out = new(string)
		**out = **in
	}
	if in.ValidRedirectUris != nil {
		in, out := &in.ValidRedirectUris, &out.ValidRedirectUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidPostLogoutRedirectUris != nil {
		in, out := &in.ValidPostLogoutRedirectUris, &out.ValidPostLogoutRedirectUris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebOrigins != nil {
		in, out := &in.WebOrigins, &out.WebOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StandardFlowEnabled != nil {
		in, out := &in.StandardFlowEnabled, &out.StandardFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ImplicitFlowEnabled != nil {
		in, out := &in.ImplicitFlowEnabled, &out.ImplicitFlowEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DirectAccessGrantsEnabled != nil {
		in, out := &in.DirectAccessGrantsEnabled, &out.DirectAccessGrantsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountsEnabled != nil {
		in, out := &in.ServiceAccountsEnabled, &out.ServiceAccountsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FullScopeAllowed != nil {
		in, out := &in.FullScopeAllowed, &out.FullScopeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.ConsentRequired != nil {
		in, out := &in.ConsentRequired, &out.ConsentRequired
		*out = new(bool)
		**out = **in
	}
	if in.AlwaysDisplayInConsole != nil {
		in, out := &in.AlwaysDisplayInConsole, &out.AlwaysDisplayInConsole
		*out = new(bool)
		**out = **in
	}
	if in.FrontchannelLogoutEnabled != nil {
		in, out := &in.FrontchannelLogoutEnabled, &out.FrontchannelLogoutEnabled
		*out = new(bool)
		**out = **in
	}
	if in.FrontchannelLogoutUrl != nil {
		in, out := &in.FrontchannelLogoutUrl, &out.FrontchannelLogoutUrl
		*out = new(string)
		**out = **in
	}
	if in.BackchannelLogoutUrl != nil {
		in, out := &in.BackchannelLogoutUrl, &out.BackchannelLogoutUrl
		*out = new(string)
		**out = **in
	}
	if in.BackchannelLogoutSessionRequired != nil {
		in, out := &in.BackchannelLogoutSessionRequired, &out.BackchannelLogoutSessionRequired
		*out = new(bool)
		**out = **in
	}
	if in.BackchannelLogoutRevokeOfflineSessions != nil {
		in, out := &in.BackchannelLogoutRevokeOfflineSessions, &out.BackchannelLogoutRevokeOfflineSessions
		*out = new(bool)
		**out = **in
	}
	if in.LoginTheme != nil {
		in, out := &in.LoginTheme, &out.LoginTheme
		*out = new(string)
		**out = **in
	}
	if in.PkceCodeChallengeMethod != nil {
		in, out := &in.PkceCodeChallengeMethod, &out.PkceCodeChallengeMethod
		*out = new(string)
		**out = **in
	}
	if in.AccessTokenLifespan != nil {
		in, out := &in.AccessTokenLifespan, &out.AccessTokenLifespan
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(ClientSecretSecretRef)
		**out = **in
	}
	if in.ExtraConfig != nil {
		in, out := &in.ExtraConfig, &out.ExtraConfig
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

// DeepCopy returns a deep copy of this ClientParameters.
func (in *ClientParameters) DeepCopy() *ClientParameters {
	if in == nil {
		return nil
	}
	out := new(ClientParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy returns a deep copy of this ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientStatus) DeepCopyInto(out *ClientStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopy returns a deep copy of this ClientStatus.
func (in *ClientStatus) DeepCopy() *ClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientList) DeepCopyInto(out *ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this ClientList.
func (in *ClientList) DeepCopy() *ClientList {
	if in == nil {
		return nil
	}
	out := new(ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientDefaultScopesParameters) DeepCopyInto(out *ClientDefaultScopesParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.ClientIdRef != nil {
		in, out := &in.ClientIdRef, &out.ClientIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientIdSelector != nil {
		in, out := &in.ClientIdSelector, &out.ClientIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientDefaultScopesSpec) DeepCopyInto(out *ClientDefaultScopesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientDefaultScopesStatus) DeepCopyInto(out *ClientDefaultScopesStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientDefaultScopes) DeepCopyInto(out *ClientDefaultScopes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this ClientDefaultScopes.
func (in *ClientDefaultScopes) DeepCopy() *ClientDefaultScopes {
	if in == nil {
		return nil
	}
	out := new(ClientDefaultScopes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClientDefaultScopes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientDefaultScopesList) DeepCopyInto(out *ClientDefaultScopesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientDefaultScopes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this ClientDefaultScopesList.
func (in *ClientDefaultScopesList) DeepCopy() *ClientDefaultScopesList {
	if in == nil {
		return nil
	}
	out := new(ClientDefaultScopesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClientDefaultScopesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientOptionalScopesParameters) DeepCopyInto(out *ClientOptionalScopesParameters) {
	*out = *in
	if in.RealmId != nil {
		in, out := &in.RealmId, &out.RealmId
		*out = new(string)
		**out = **in
	}
	if in.RealmIdRef != nil {
		in, out := &in.RealmIdRef, &out.RealmIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.RealmIdSelector != nil {
		in, out := &in.RealmIdSelector, &out.RealmIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.ClientIdRef != nil {
		in, out := &in.ClientIdRef, &out.ClientIdRef
		*out = new(xpv1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientIdSelector != nil {
		in, out := &in.ClientIdSelector, &out.ClientIdSelector
		*out = new(xpv1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.OptionalScopes != nil {
		in, out := &in.OptionalScopes, &out.OptionalScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientOptionalScopesSpec) DeepCopyInto(out *ClientOptionalScopesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientOptionalScopesStatus) DeepCopyInto(out *ClientOptionalScopesStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientOptionalScopes) DeepCopyInto(out *ClientOptionalScopes) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this ClientOptionalScopes.
func (in *ClientOptionalScopes) DeepCopy() *ClientOptionalScopes {
	if in == nil {
		return nil
	}
	out := new(ClientOptionalScopes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClientOptionalScopes) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ClientOptionalScopesList) DeepCopyInto(out *ClientOptionalScopesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClientOptionalScopes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this ClientOptionalScopesList.
func (in *ClientOptionalScopesList) DeepCopy() *ClientOptionalScopesList {
	if in == nil {
		return nil
	}
	out := new(ClientOptionalScopesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ClientOptionalScopesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
