apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
  annotations:
    meta.crossplane.io/maintainer: Ross Golder <ross@golder.org>
    meta.crossplane.io/source: github.com/rossigee/provider-keycloak
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Crossplane provider for Keycloak
spec:
  package: ghcr.io/rossigee/provider-keycloak:dev-cd7b0fe
  packagePullPolicy: IfNotPresent
