apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-keycloak
  annotations:
    meta.crossplane.io/maintainer: Ross Golder <ross@golder.org>
    meta.crossplane.io/source: github.com/rossigee/provider-keycloak
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A template that can be used to create Crossplane providers.
spec:
  version: "0.1.0-test-51f0dce"
